/*
* 用于编译的变量文件
* 科技色变量：如techBlue,techGreen，
*/
module.exports = {
  // '@primary-color': '#36B3C8',
  '@primary-color-secondary': '#00D2FF',
  '@info-color': '#1890ff',
  '@success-color': '#4DC9A5',
  '@processing-color': '#548DFF',
  '@error-color': '#FF6252',
  '@warning-color': '#FEA371',
  '@normal-color': '#acbbbd',
  '@highlight-color': '#fb2727',
  '@white': '#fff',
  '@black': '#000',

  // ________
  '@primary-1': 'color(~`colorPalette("@{primary-color}", 1) `)', // replace tint(@primary-color, 90%)
  '@primary-2': 'color(~`colorPalette("@{primary-color}", 2) `)', // replace tint(@primary-color, 80%)
  '@primary-3': 'color(~`colorPalette("@{primary-color}", 3) `)', // unused
  '@primary-4': 'color(~`colorPalette("@{primary-color}", 4) `)', // unused
  '@primary-5': 'color(~`colorPalette("@{primary-color}", 5) `)', // color used to control the text color in many active and hover states, replace tint(@primary-color, 20%)
  '@primary-6': '@primary-color', // color used to control the text color of active buttons, don't use, use @primary-color
  '@primary-7': 'color(~`colorPalette("@{primary-color}", 7) `)', // replace shade(@primary-color, 5%)
  '@primary-8': 'color(~`colorPalette("@{primary-color}", 8) `)', // unused
  '@primary-9': 'color(~`colorPalette("@{primary-color}", 9) `)', // unused
  '@primary-10': 'color(~`colorPalette("@{primary-color}", 10) `)', // unused

// Background color for `<body>`
  '@body-background': 'transparent',
  // Base background color for most components
  '@component-background': '#103B43', // 'fade(#00090A, 85%)' '#103b43',
  // '@font-family': 'Microsoft YaHei',
  '@text-color': '#ffffff',
  '@text-color-secondary': 'fade(#fff, 65%)',
  '@text-color-dark': '#fff',
  '@icon-color-hover': 'fade(#fff, 80%)',
  '@text-color-secondary-dark': 'fade(#fff, 30%)',
  '@heading-color': '#ffffff',
  '@heading-color-dark': 'fade(#fff, 50%)',

  // Border color
  '@border-color-base': 'fade(@primary-color, 40%)',
  '@border-color-split': 'fade(@primary-color, 20%)',
  '@border-color-split-popover': 'fade(#EBEBF0, 30%)',
  '@border-color-inverse': '#F3F3F8',

// Disabled states
  '@disabled-color': 'fade(#ffffff, 40%)',
  '@disabled-bg': '@background-color-base',
  '@disabled-color-dark': 'fade(#ffffff, 30%)',
// Shadow
  '@shadow-color': 'rgba(0, 9, 10, 0.15)',

// Buttons
  '@btn-primary-color': '#fff',
  '@btn-primary-bg': 'fade(@primary-color-secondary, 90%)',
  '@btn-default-color': '@text-color',
  '@btn-default-bg': 'transparent',
  '@btn-default-border': '@border-color-base',
  // '@btn-danger-color': '#fff',
  // '@btn-danger-bg': '@error-color',
  // '@btn-danger-border': '@error-color',
  // '@btn-disable-color': '@disabled-color',
  // '@btn-disable-bg': '@disabled-bg',
  // '@btn-disable-border': '@border-color-split',
  '@btn-default-ghost-color': '@text-color',
  '@btn-default-ghost-bg': 'transparent',
  '@btn-default-ghost-border': 'fade(#ffffff, 25%)',
  // '@btn-padding-base': '0 @padding-md - 1px',
  '@btn-font-size-lg': '@font-size-lg',
  '@btn-font-size-sm': '@font-size-base',
  '@btn-padding-lg': '@btn-padding-base',
  '@btn-padding-sm': '0 @padding-xs - 1px',
  // '@btn-height-base': '32px',
  // '@btn-height-lg': '40px',
  '@btn-height-sm': '24px',
  '@btn-circle-size': '@btn-height-base',
  '@btn-circle-size-lg': '@btn-height-lg',
  '@btn-circle-size-sm': '@btn-height-sm',
  '@btn-square-size': '@btn-height-base',
  '@btn-square-size-lg': '@btn-height-lg',
  '@btn-square-size-sm': '@btn-height-sm',
  '@btn-group-border': '@primary-5',

  '@layout-trigger-background': '#fa00e1',
  '@layout-trigger-color': '#fa0083',
  '@layout-sider-background-light': '#2f54eb',

  '@background-color-light': 'fade(@primary-color, 10%)',
  // '@background-color-light': 'fade(@primary-color, 4%)',
  '@background-color-base': 'fade(@primary-color, 20%)',
  '@item-active-bg': '@primary-6',
  '@item-hover-bg': 'fade(@primary-color, 20%)',
  '@input-placeholder-color': 'fade(#FFFFFF, 50%)',
  '@input-bg': 'transparent',
  '@select-item-selected-bg': '@primary-color',
  // '@tooltip-bg': '#434343',
  '@modal-header-bg': '@primary-color',
  '@menu-bg': 'fade(#000, 70%)',
  '@menu-popup-bg': '@popover-background',
  '@menu-item-active-bg': 'fade(@primary-color, 70%)',
  '@menu-dark-bg': 'fade(#00090A, 50%)',
  '@table-header-bg': 'fade(@primary-color-secondary, 15%)',
  '@table-body-sort-bg': 'fade(#ffffff, 1%)',
  '@table-row-hover-bg': 'fade(@primary-color, 10%)',
  '@table-expanded-row-bg': 'fade(@primary-color, 2%)',
  '@table-padding-vertical': '14px',
  '@table-padding-horizontal': '8px',

  // '@table-header-bg': '#E8EEF3',
  // 'table-header-color': '#000',
  // '@table-row-hover-bg': 'fade(@table-header-bg, 10%)',
  // '@table-expanded-row-bg': '#f9f9fb',
  // '@table-padding-vertical': '14px',
  // '@table-padding-horizontal': '8px',

  '@table-bg': '@component-background',
  // '@table-header-bg': '#1d1d1d',
  '@table-header-color': '@heading-color',
  // '@table-header-sort-bg': '#262626',
  // '@table-body-sort-bg': 'fade(#ffffff, 1%)',
  // '@table-row-hover-bg': '#262626',
  '@table-selected-row-color': 'inherit',
  '@table-selected-row-bg': '@item-hover-bg',
  '@table-body-selected-sort-bg': '@table-selected-row-bg',
  '@table-selected-row-hover-bg': '@table-selected-row-bg',
  // '@table-expanded-row-bg': '#fbfbfb',
  // '@table-padding-vertical': '16px',
  // '@table-padding-horizontal': '8px',
  '@table-border-radius-base': '@border-radius-base',
  '@table-footer-bg': '@background-color-light',
  '@table-footer-color': '@heading-color',
  '@table-header-bg-sm': '@table-header-bg',
  '@table-header-sort-active-bg': '#262626',
  '@table-header-filter-active-bg': '#434343',
  '@table-filter-btns-bg': '@popover-background',

  '@pagination-item-bg-active': 'fade(@primary-color, 50%)',
  '@tree-node-selected-bg': '@primary-5',
  '@transfer-item-hover-bg': 'fade(@primary-color, 20%)',
  '@alert-success-border-color': '@success-color',
  '@alert-success-bg-color': 'fade(@success-color, 30%)',
  '@alert-info-border-color': '@info-color',
  '@alert-info-bg-color': 'fade(@info-color, 30%)',
  '@alert-warning-border-color': '@warning-color',
  '@alert-warning-bg-color': 'fade(@warning-color, 30%)',
  '@alert-error-border-color': '@error-color',
  '@alert-error-bg-color': 'fade(@error-color, 30%)',

  // layout
  '@layout-body-background': 'fade(@primary-color, 15%)',
  '@layout-header-background': 'fade(#00090A, 50%)',
  '@layout-header-height': '56px',
  // '@layout-header-padding': '0 0px',
  '@layout-sider-background': '@component-background',

  // Base background color for most components
  // '@body-background': '#f82915',
  // '@font-family': 'Microsoft YaHei',
  // '@text-color': '#fff',
  // '@text-color-secondary': '#9098B1',
  // '@text-color-dark': '#4C5E76',
  // '@text-color-secondary-dark': '#CDDBE8',
  // '@heading-color': '@text-color-dark',
  // '@font-size-base': '14px',
  // '@heading-4-size': '20px',
  // '@line-height-base': '1.4',

  // '@background-color-light': '@fade(@primary-color, 15%)',

  // vertical paddings
  // '@padding-lg': '20px',
  // '@padding-md': '16px',
  // '@padding-sm': '12px',
  // '@padding-xs': '8px',
  // vertical padding for all form controls
  '@control-padding-horizontal': '8px',
  // Border color
  // '@border-color-base': '#D7D7E3', // #EBEBF0
  // '@border-color-split': 'rgba(238, 238, 238, 0.71)',
  // Form
  // ---
  '@label-color': '@text-color', // 同'text-color

  // Buttons
  // '@btn-padding-base': '0 16px',
  // '@btn-height-base': '32px',
  // '@btn-height-lg': '36px',
  // '@btn-font-size-sm': '14px',

  // Input
  // ---
  // '@input-height-base': '32px',
  // '@input-height-lg': '36px',
  // '@input-padding-horizontal': '8px', // 8px
  // '@input-padding-horizontal-lg': '16px',

  // '@form-item-margin-bottom': '16px',
  // Menu
  // ---
  // '@menu-inline-toplevel-item-height': '72px',
  // '@menu-item-height': '72px',
  '@menu-icon-size': '24px',
  '@menu-item-active-border-width': '4px',
  // '@menu-item-active-bg': '#1A2634',
  // '@menu-highlight-color': '#fff',
  '@menu-dark-color': 'color(~`colorPalette("@{primary-color}", 4)`)',
  // '@menu-dark-bg': 'url(\'/images/sideer-bg.png\') #143179 left bottom no-repeat',
  // dark theme Menu
  // '@menu-dark-bg': '#263548',
  '@menu-dark-arrow-color': 'color(~`colorPalette("@{primary-color}", 4)`)',
  '@menu-dark-submenu-bg': 'transparent',
  '@menu-dark-highlight-color': '@primary-color',
  '@menu-dark-item-active-bg': 'fade(@primary-color, 30%)',
  '@menu-dark-selected-item-icon-color': '@primary-color',
  '@menu-dark-selected-item-text-color': '@primary-color',


  // '@pagination-item-size': '30px',
  '@breadcrumb-last-item-color': '@text-color-dark',
  // Tag
  // '@tag-font-size': '12px',
  // modal
  // '@modal-header-bg': '#43dcf6',
  '@modal-body-padding': '@padding-md @padding-lg', // 16px 20px


  // tabs
  // '@tabs-card-height': '32px',
  '@tabs-card-active-color': '@text-color',
  '@tabs-hover-color': '@text-color',
  // '@tabs-card-gutter': '-1px',

  // '@component-background': '#141414',
  // '@grid-columns': '24',
  '@popover-background': '#1F6471',

  // '@body-background': '#357a27',
  // '@text-color': 'fade(#ffffff, 65%)',
  // '@text-color-secondary': 'fade(#ffffff, 45%)',
  '@text-color-inverse': '#ffffff',
  '@icon-color': 'inherit',
  // '@icon-color-hover': 'fade(#ffffff, 75%)',
  // '@heading-color': 'fade(#ffffff, 85%)',
  // '@heading-color-dark': 'fade(#ffffff, 100%)',
  // '@text-color-dark': 'fade(#ffffff, 85%)',
  // '@text-color-secondary-dark': 'fade(#ffffff, 65%)',
  '@text-selection-bg': '@primary-color',
  '@font-variant-base': 'tabular-nums',
  '@font-feature-settings-base': 'tnum',
  // '@font-size-base': '14px',
  '@font-size-lg': '@font-size-base + 2px',
  '@font-size-sm': '12px',
  '@heading-1-size': 'ceil(@font-size-base * 2.71)',
  '@heading-2-size': 'ceil(@font-size-base * 2.14)',
  '@heading-3-size': 'ceil(@font-size-base * 1.71)',
  // '@heading-4-size': 'ceil(@font-size-base * 1.42)',
  '@line-height-base': '1.4',
  '@border-radius-base': '2px',

  // '@control-padding-horizontal': '@padding-sm',
  '@control-padding-horizontal-sm': '@padding-xs',
  // '@item-active-bg': '@primary-1',
  // '@item-hover-bg': 'fade(#ffffff, 8%)',
  // '@iconfont-css-prefix': 'anticon',
  '@link-color': '@primary-color-secondary',
  // '@link-hover-color': '@blue-5',
  // '@link-active-color': '@blue-7',
  // '@link-decoration': 'none',
  // '@link-hover-decoration': 'none',
  // '@ease-base-out': 'cubic-bezier(0.7, 0.3, 0.1, 1)',
  // '@ease-base-in': 'cubic-bezier(0.9, 0, 0.3, 0.7)',
  // '@ease-out': 'cubic-bezier(0.215, 0.61, 0.355, 1)',
  // '@ease-in': 'cubic-bezier(0.55, 0.055, 0.675, 0.19)',
  // '@ease-in-out': 'cubic-bezier(0.645, 0.045, 0.355, 1)',
  // '@ease-out-back': 'cubic-bezier(0.12, 0.4, 0.29, 1.46)',
  // '@ease-in-back': 'cubic-bezier(0.71, -0.46, 0.88, 0.6)',
  // '@ease-in-out-back': 'cubic-bezier(0.71, -0.46, 0.29, 1.46)',
  // '@ease-out-circ': 'cubic-bezier(0.08, 0.82, 0.17, 1)',
  // '@ease-in-circ': 'cubic-bezier(0.6, 0.04, 0.98, 0.34)',
  // '@ease-in-out-circ': 'cubic-bezier(0.78, 0.14, 0.15, 0.86)',
  // '@ease-out-quint': 'cubic-bezier(0.23, 1, 0.32, 1)',
  // '@ease-in-quint': 'cubic-bezier(0.755, 0.05, 0.855, 0.06)',
  // '@ease-in-out-quint': 'cubic-bezier(0.86, 0, 0.07, 1)',
  // '@border-color-base': '#434343',
  // '@border-color-split': '@popover-background',

  // '@border-width-base': '1px',
  // '@border-style-base': 'solid',
  // '@outline-blur-size': '0',
  // '@outline-width': '2px',
  // '@outline-color': '@primary-color',
  // '@background-color-light': 'fade(#ffffff, 4%)',
  '@box-shadow-base': '0 0 12px fade(@primary-color, 10%)',
  '@shadow-color-inverse': '@component-background',
  // '@box-shadow-base': '@shadow-2',
  // '@shadow-1-up': '0 -6px 16px -8px rgba(0, 0, 0, 0.24), 0 -9px 28px 0 rgba(0, 0, 0, 0.15),\n  0 -12px 48px 16px rgba(0, 0, 0, 0.09)',
  // '@shadow-1-down': '0 6px 16px -8px rgba(0, 0, 0, 0.24), 0 9px 28px 0 rgba(0, 0, 0, 0.15),\n  0 12px 48px 16px rgba(0, 0, 0, 0.09)',
  // '@shadow-1-left': '-6px 0 16px -8px rgba(0, 0, 0, 0.08), -9px 0 28px 0 rgba(0, 0, 0, 0.05),\n  -12px 0 48px 16px rgba(0, 0, 0, 0.03)',
  // '@shadow-1-right': '6px 0 16px -8px rgba(0, 0, 0, 0.24), 9px 0 28px 0 rgba(0, 0, 0, 0.15),\n  12px 0 48px 16px rgba(0, 0, 0, 0.09)',
  // '@shadow-2': '0 3px 6px -4px rgba(0, 0, 0, 0.36), 0 6px 16px 0 rgba(0, 0, 0, 0.24),\n  0 9px 28px 8px rgba(0, 0, 0, 0.15)',
  // '@btn-font-weight': '400',
  // '@btn-border-radius-base': '@border-radius-base',
  // '@btn-border-radius-sm': '@border-radius-base',
  // '@btn-border-width': '@border-width-base',
  // '@btn-border-style': '@border-style-base',

  '@checkbox-size': '16px',
  '@checkbox-color': '@primary-color',
  '@checkbox-check-color': '#fff',
  '@checkbox-check-bg': 'transparent',
  // '@checkbox-border-width': '@border-width-base',
  '@descriptions-bg': '@component-background',
  '@dropdown-selected-color': '@primary-color',
  '@dropdown-menu-submenu-disabled-bg': 'transparent',
  '@empty-font-size': '@font-size-base',
  // '@radio-size': '16px',
  // '@radio-dot-color': '@primary-color',
  '@radio-dot-disabled-color': 'fade(#ffffff, 20%)',
  '@radtio-solid-checked-color': '#ffffff',
  '@radio-button-bg': '@btn-default-bg',
  '@radio-button-checked-bg': '@btn-default-bg',
  '@radio-button-color': '@btn-default-color',
  '@radio-button-hover-color': '@primary-5',
  '@radio-button-active-color': '@primary-7',
  '@radio-disabled-button-checked-bg': 'fade(#ffffff, 20%)',
  '@radio-disabled-button-checked-color': 'fade(#ffffff, 25%)',
  // '@layout-body-background': '@body-background',
  // '@layout-header-background': '@component-background',
  '@layout-footer-background': '@layout-body-background',
  // '@layout-header-height': '64px',
  // '@layout-header-padding': '0 50px',
  // '@layout-footer-padding': '24px 50px',
  // '@layout-sider-background': '@component-background',
  // '@layout-trigger-height': '48px',
  // '@layout-trigger-background': '@component-background',
  // '@layout-trigger-color': '#fff',
  // '@layout-zero-trigger-width': '36px',
  // '@layout-zero-trigger-height': '42px',
  // '@layout-sider-background-light': '#fff',
  // '@layout-trigger-background-light': '#fff',
  // '@layout-trigger-color-light': '@text-color',
  '@collapse-panel-border-radius': '@border-radius-base',
  // '@dropdown-menu-bg': '@popover-background',
  // '@dropdown-vertical-padding': '5px',
  // '@dropdown-font-size': '@font-size-base',
  // '@dropdown-line-height': '22px',
  // '@label-required-color': '@highlight-color',
  // '@label-color': '@heading-color',
  // '@form-warning-input-bg': '@input-bg',
  // '@form-item-margin-bottom': '24px',
  // '@form-item-trailing-colon': 'true',
  // '@form-vertical-label-padding': '0 0 8px',
  // '@form-vertical-label-margin': '0',
  // '@form-item-label-colon-margin-right': '8px',
  // '@form-item-label-colon-margin-left': '2px',
  // '@form-error-input-bg': '@input-bg',
  // '@input-height-base': '32px',
  // '@input-height-lg': '40px',
  // '@input-height-sm': '24px',
  // '@input-padding-horizontal': '@control-padding-horizontal - 1px',
  '@input-padding-horizontal-base': '@input-padding-horizontal',
  '@input-padding-horizontal-sm': '@control-padding-horizontal-sm - 1px',
  '@input-padding-horizontal-lg': '@input-padding-horizontal',
  '@input-padding-vertical-base': '4px',
  '@input-padding-vertical-sm': '1px',
  '@input-padding-vertical-lg': '6px',
  // '@input-placeholder-color': 'fade(#ffffff, 30%)',
  '@input-color': '@text-color',
  '@input-border-color': '@border-color-base',
  // '@input-bg': 'transparent',
  '@input-number-hover-border-color': '@input-hover-border-color',
  '@input-number-handler-active-bg': '@popover-background',
  '@input-number-handler-hover-bg': '@primary-5',
  '@input-number-handler-bg': 'transparent',
  '@input-number-handler-border-color': '@border-color-base',
  '@input-addon-bg': '@background-color-light',
  '@input-hover-border-color': '@primary-5',
  '@input-disabled-bg': '@disabled-bg',
  '@input-outline-offset': '0 0',
  '@input-icon-hover-color': 'fade(#ffffff, 85%)',
  '@mentions-dropdown-bg': '@popover-background',
  '@select-border-color': '@border-color-base',
  '@select-item-selected-font-weight': '600',
  '@select-dropdown-bg': '@popover-background',
  // '@select-item-selected-bg': '@blue-1',
  '@select-item-active-bg': '@item-hover-bg',
  '@select-background': 'transparent',
  '@select-clear-background': '@component-background',
  '@cascader-bg': 'transparent',
  // '@cascader-item-selected-bg': '@blue-1',
  '@cascader-menu-bg': '@popover-background',
  '@cascader-menu-border-color-split': '@border-color-split-popover',
  '@anchor-bg': 'inherit',
  '@anchor-border-color': '@border-color-split',
  '@tooltip-max-width': '250px',
  '@tooltip-color': '#fff',
  '@tooltip-bg': '#434343',
  '@tooltip-arrow-width': '5px',
  '@tooltip-distance': '@tooltip-arrow-width - 1px + 4px',
  '@tooltip-arrow-color': '@tooltip-bg',
  '@popover-bg': '@popover-background',
  '@popover-color': '@text-color',
  '@popover-min-width': '177px',
  '@popover-arrow-width': '6px',
  '@popover-arrow-color': '@popover-bg',
  '@popover-arrow-outer-color': '@popover-bg',
  '@popover-distance': '@popover-arrow-width + 4px',
  // '@modal-body-padding': '24px',
  // '@modal-header-bg': '@popover-background',
  '@modal-header-border-color-split': '@border-color-split-popover',
  '@modal-content-bg': '@popover-background',
  '@modal-heading-color': '@heading-color',
  '@modal-footer-bg': 'transparent',
  '@modal-footer-border-color-split': '@border-color-split-popover',
  '@modal-mask-bg': 'fade(@black, 45%)',
  '@progress-default-color': '@processing-color',
  '@progress-remaining-color': '@background-color-base',
  '@progress-text-color': '@text-color',
  '@progress-radius': '100px',
  // '@menu-inline-toplevel-item-height': '40px',
  '@menu-item-height': '72px',
  '@menu-collapsed-width': '80px',
  // '@menu-bg': '@component-background',
  // '@menu-popup-bg': '@popover-background',
  '@menu-item-color': '@text-color',
  '@menu-highlight-color': '@primary-color',
  // '@menu-item-active-bg': '@primary-1',
  // '@menu-item-active-border-width': '3px',
  '@menu-item-group-title-color': '@text-color-secondary',
  // '@menu-icon-size': '@font-size-base',
  '@menu-icon-size-lg': '@font-size-lg',
  '@menu-item-vertical-margin': '4px',
  '@menu-item-font-size': '@font-size-base',
  '@menu-item-boundary-margin': '8px',
  // '@menu-dark-color': '@text-color-secondary-dark',
  // '@menu-dark-bg': '@layout-header-background',
  // '@menu-dark-arrow-color': '#fff',
  // '@menu-dark-submenu-bg': '@black',
  // '@menu-dark-highlight-color': '#fff',
  // '@menu-dark-item-active-bg': '@primary-color',
  // '@menu-dark-selected-item-icon-color': '#ffffff',
  // '@menu-dark-selected-item-text-color': '#ffffff',
  '@menu-dark-item-hover-bg': 'transparent',
  '@spin-dot-size-sm': '14px',
  '@spin-dot-size': '20px',
  '@spin-dot-size-lg': '32px',

  '@tag-default-bg': '@background-color-light',
  '@tag-default-color': '@text-color',
  // '@tag-font-size': '@font-size-sm',
  '@time-picker-bg': '@popover-background',
  '@time-picker-panel-column-width': '56px',
  '@time-picker-panel-width': '@time-picker-panel-column-width * 3',
  '@time-picker-selected-bg': '@item-active-bg',
  '@time-picker-inner-bg': '@popover-background',
  '@time-picker-panel-inner-bg': '@popover-background',
  '@month-panel-bg': '@popover-background',
  '@year-panel-bg': '@popover-background',
  '@calendar-bg': '@popover-background',
  '@calendar-input-bg': '@calendar-bg',
  '@calendar-border-color': 'transparent',
  '@calendar-item-active-bg': '@background-color-base',
  '@carousel-dot-width': '16px',
  '@carousel-dot-height': '3px',
  '@carousel-dot-active-width': '24px',
  '@badge-height': '20px',
  '@badge-dot-size': '6px',
  '@badge-font-size': '@font-size-sm',
  '@badge-font-weight': 'normal',
  '@badge-status-size': '6px',
  '@badge-text-color': '#ffffff',
  '@rate-star-bg': '@border-color-split',
  // card
  '@card-head-color': '@text-color-dark',
  // '@card-head-color': '@heading-color',
  '@card-head-background': 'transparent',
  // '@card-head-padding': '16px',
  // '@card-inner-head-padding': '12px',
  // '@card-padding-base': '24px',
  '@card-actions-background': 'fade(#ffffff, 4%)',
  '@card-skeleton-bg': '#303030',
  '@card-background': 'transparent', // '@layout-body-background',
  // '@card-shadow': '0 1px 2px -2px rgba(0, 0, 0, 0.48), 0 3px 6px 0 rgba(0, 0, 0, 0.36),\n  0 5px 12px 4px rgba(0, 0, 0, 0.27)',
  '@card-radius': '@border-radius-base',
  '@comment-bg': '@component-background',
  '@comment-padding-base': '16px 0',
  '@comment-nest-indent': '44px',
  '@comment-font-size-base': '@font-size-base',
  '@comment-font-size-sm': '@font-size-sm',
  '@comment-author-name-color': '@text-color-secondary',
  '@comment-author-time-color': '#ccc',
  '@comment-action-color': '@text-color-secondary',
  '@comment-action-hover-color': '#595959',
  '@tabs-card-head-background': '@background-color-light',
  '@tabs-card-height': '32px',
  // '@tabs-card-active-color': '@primary-color',
  '@tabs-title-font-size': '@font-size-base',
  '@tabs-title-font-size-lg': '@font-size-lg',
  '@tabs-title-font-size-sm': '@font-size-base',
  '@tabs-ink-bar-color': '@primary-color',
  // '@tabs-bar-margin': '0 0 16px 0',
  // '@tabs-horizontal-margin': '0 32px 0 0',
  // '@tabs-horizontal-padding': '12px 16px',
  // '@tabs-horizontal-padding-lg': '16px',
  // '@tabs-horizontal-padding-sm': '8px 16px',
  // '@tabs-vertical-padding': '8px 24px',
  // '@tabs-vertical-margin': '0 0 16px 0',
  '@tabs-scrolling-size': '32px',
  '@tabs-highlight-color': '@primary-color',
  // '@tabs-hover-color': '@primary-5',
  '@tabs-active-color': '@primary-7',
  // '@tabs-card-gutter': '2px',
  '@tabs-card-tab-active-border-top': '2px solid transparent',
  // '@back-top-color': '#fff',
  // '@back-top-bg': '@text-color-secondary',
  // '@back-top-hover-bg': '@text-color',
  // '@avatar-size-base': '32px',
  // '@avatar-size-lg': '40px',
  // '@avatar-size-sm': '24px',
  // '@avatar-font-size-base': '18px',
  // '@avatar-font-size-lg': '24px',
  // '@avatar-font-size-sm': '14px',
  '@avatar-bg': '#5a5a5a',
  '@avatar-color': '#fff',
  // '@avatar-border-radius': '@border-radius-base',
  // '@switch-height': '22px',
  // '@switch-sm-height': '16px',
  // '@switch-sm-checked-margin-left': '-(@switch-sm-height - 3px)',
  '@switch-disabled-opacity': '0.4',
  '@switch-color': '@primary-color-secondary',
  '@switch-bg': '#ffffff',
  '@switch-shadow-color': 'fade(#fff, 20%)',
  '@pagination-item-bg': 'transparent',
  // '@pagination-item-size': '32px',
  // '@pagination-item-size-sm': '24px',
  // '@pagination-font-family': 'Arial',
  // '@pagination-font-weight-active': '500',
  // '@pagination-item-bg-active': 'transparent',
  '@pagination-item-link-bg': 'transparent',
  '@pagination-item-disabled-color-active': '@black',
  '@pagination-item-disabled-bg-active': 'fade(#ffffff, 25%)',
  // '@page-header-padding': '24px',
  // '@page-header-padding-vertical': '16px',
  // '@page-header-padding-breadcrumb': '12px',
  // '@page-header-back-color': '@icon-color',
  '@breadcrumb-base-color': '@text-color-secondary',
  // '@breadcrumb-last-item-color': '@text-color',
  '@breadcrumb-font-size': '@font-size-base',
  '@breadcrumb-icon-font-size': '@font-size-base',
  '@breadcrumb-link-color': '@text-color-secondary',
  '@breadcrumb-link-color-hover': '@primary-5',
  '@breadcrumb-separator-color': '@text-color-secondary',
  '@breadcrumb-separator-margin': '0 @padding-xs',
  '@slider-margin': '14px 6px 10px',
  '@slider-rail-background-color': 'fade(#ffffff, 20%)',
  '@slider-rail-background-color-hover': '@slider-rail-background-color',
  '@slider-track-background-color': '@primary-color',
  '@slider-track-background-color-hover': '@primary-4',
  '@slider-handle-border-width': '2px',
  '@slider-handle-background-color': '@component-background',
  '@slider-handle-color': '@primary-color',
  '@slider-handle-color-hover': '@primary-4',
  '@slider-handle-color-focus': 'tint(@primary-color, 20%)',
  '@slider-handle-color-focus-shadow': 'fade(@primary-color, 20%)',
  '@slider-handle-color-tooltip-open': '@primary-color',
  '@slider-handle-shadow': '0',
  '@slider-dot-border-color': '@border-color-split',
  '@slider-dot-border-color-active': 'tint(@primary-color, 50%)',
  '@slider-disabled-color': '@disabled-color',
  '@slider-disabled-background-color': '@component-background',
  '@tree-bg': 'transparent',
  '@tree-title-height': '24px',
  '@tree-child-padding': '18px',
  '@tree-directory-selected-color': '#fff',
  '@tree-directory-selected-bg': '@primary-color',
  '@tree-node-hover-bg': '@item-hover-bg',
  // '@tree-node-selected-bg': '@primary-2',
  '@collapse-header-padding': '12px 16px',
  '@collapse-header-padding-extra': '40px',
  '@collapse-header-bg': '@background-color-light',
  '@collapse-content-padding': '@padding-md',
  '@collapse-content-bg': '@component-background',
  '@skeleton-color': '#303030',
  '@skeleton-to-color': 'fade(#ffffff, 16%)',
  '@transfer-header-height': '40px',
  '@transfer-disabled-bg': '@disabled-bg',
  '@transfer-list-height': '200px',
  // '@transfer-item-hover-bg': '#262626',
  '@message-notice-content-padding': '10px 16px',
  '@message-notice-content-bg': '@popover-background',
  '@wave-animation-width': '6px',
  // '@alert-success-border-color': '@green-3',
  // '@alert-success-bg-color': '@green-1',
  '@alert-success-icon-color': '@success-color',
  // '@alert-info-border-color': '@blue-3',
  // '@alert-info-bg-color': '@blue-1',
  '@alert-info-icon-color': '@info-color',
  // '@alert-warning-border-color': '@gold-3',
  // '@alert-warning-bg-color': '@gold-1',
  '@alert-warning-icon-color': '@warning-color',
  // '@alert-error-border-color': '@red-3',
  // '@alert-error-bg-color': '@red-1',
  '@alert-error-icon-color': '@error-color',
  '@list-header-background': 'transparent',
  '@list-footer-background': 'transparent',
  '@list-empty-text-padding': '@padding-md',
  '@list-item-padding': '@padding-sm 0',
  '@list-item-meta-margin-bottom': '@padding-md',
  '@list-item-meta-avatar-margin-right': '@padding-md',
  '@list-item-meta-title-margin-bottom': '@padding-sm',
  '@statistic-title-font-size': '@font-size-base',
  '@statistic-content-font-size': '24px',
  '@statistic-unit-font-size': '16px',
  '@statistic-font-family': '@font-family',
  '@drawer-header-padding': '16px 20px',
  '@drawer-body-padding': '24px',
  '@drawer-bg': '@popover-background',
  '@timeline-width': '2px',
  '@timeline-color': '@border-color-split',
  '@timeline-dot-border-width': '2px',
  '@timeline-dot-color': '@primary-color',
  '@timeline-dot-bg': 'transparent',
  '@typography-title-font-weight': '600',
  '@typography-title-margin-top': '1.2em',
  '@typography-title-margin-bottom': '0.5em',
  '@upload-actions-color': '@text-color-secondary',
  '@process-tail-color': 'fade(#ffffff, 20%)',
  '@steps-nav-arrow-color': 'fade(#ffffff, 20%)',
  '@notification-bg': '@popover-background',

  '@zindex-message': 2010,

};
